name: Android tests

on: [ push ]

jobs:

  AndroidTests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest ]
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - run: bash ./gradlew managedVirtualDeviceCheck -Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect --stacktrace

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screenshots
          path: ${{ github.workspace }}/**/build/tmp/shot/screenshot/*
