name: Android tests

on: [ push ]

jobs:

  jobLint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2.0.0

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'

      - uses: ReactiveCircus/android-emulator-runner@v2.19.1
        with:
          api-level: 28
          target: default
          arch: x86
          profile: Nexus 6
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          disable-animations: true
          script: ./gradlew connectedAndroidTest
