name: Android build

on: [ push ]

jobs:

  Lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - run: bash ./gradlew ciLint --stacktrace


  UnitTest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - run: bash ./gradlew ciUnitTest --stacktrace


  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - run: bash ./gradlew ciBuildApp --stacktrace

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: apk_aar
          path: |
            **/*.apk
            **/*.aar
