name: Android build

on: [ push ]

jobs:

  jobLint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2.0.0

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'

      - run: bash ./gradlew clean ktlintCheck --stacktrace


  jobUnitTest:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2.0.0

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'

      - run: bash ./gradlew clean testDebug --stacktrace


  jobBuild:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2.0.0

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'

      - run: bash ./gradlew clean assembleDebug --stacktrace

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: apk_aar
          path: |
            **/*.apk
            **/*.aar
