name: Android tests

on: [ push ]

jobs:

  AndroidTests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest ]
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: aosp_atd
          arch: x86
          profile: Nexus 6
          channel: canary
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew ciEmulator

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screenshots
          path: ${{ github.workspace }}/**/build/tmp/shot/screenshot/*
