name: Android tests

on: [ push ]

jobs:

  jobAndroidTests:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2.0.0

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'

      - uses: ReactiveCircus/android-emulator-runner@v2.21.0
        with:
          api-level: 30
          target: aosp_atd
          arch: x86
          profile: Nexus 6
          channel: canary
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          disable-animations: true
          script: ./gradlew connectedAndroidTest

#      - run: bash ./gradlew clean testEmulator28Check --stacktrace
