name: CI

on: [ push ]

env:
  JAVA_VERSION: 20

jobs:


  Lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - uses: android-actions/setup-android@v3

      - run: bash ./gradlew ciLint --stacktrace


  UnitTest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - uses: android-actions/setup-android@v3

      - run: bash ./gradlew ciUnitTest --stacktrace


  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - uses: android-actions/setup-android@v3

      - run: bash ./gradlew ciBuildApp --stacktrace




  AndroidTests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    steps:

      - uses: actions/checkout@v4

      - name: Enable KVM group perms
        if: contains(matrix.os, 'ubuntu')
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - uses: android-actions/setup-android@v3

      - run: bash ./gradlew ciEmulator --stacktrace

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: ${{ github.workspace }}/**/build/tmp/shot/screenshot/*


  jobIosTests:
    runs-on: macos-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - uses: android-actions/setup-android@v3

      - run: xcodebuild -project "iosApp/iosApp.xcodeproj" -scheme iosApp test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12'

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: tests.xcresult
          path: /Users/runner/Library/Developer/Xcode/DerivedData/*/Logs/Test/*.xcresult

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: spm
          path: shared/build/spm/
