name: CI

on: [ push ]

jobs:


  Lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: android-actions/setup-android@v2

      - run: bash ./gradlew ciLint --stacktrace


  UnitTest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: android-actions/setup-android@v2

      - run: bash ./gradlew ciUnitTest --stacktrace


  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: android-actions/setup-android@v2

      - run: bash ./gradlew ciBuildApp --stacktrace

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: apk_aar
          path: |
            **/*.apk
            **/*.aar




  AndroidTests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest ]
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: android-actions/setup-android@v2

      - uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: aosp_atd
          arch: x86
          profile: Nexus 6
          channel: canary
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew ciEmulator

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screenshots
          path: ${{ github.workspace }}/**/build/tmp/shot/screenshot/*


  jobIosTests:
    runs-on: macos-11

    steps:
      - uses: devbotsxyz/xcode-select@v1

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: android-actions/setup-android@v2

      - run: xcodebuild -project "iosApp/iosApp.xcodeproj" -scheme iosApp test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12'

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: tests.xcresult
          path: /Users/runner/Library/Developer/Xcode/DerivedData/*/Logs/Test/*.xcresult

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: spm
          path: shared/build/spm/
