name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: ci
      run: bash ./gradlew clean build test --stacktrace

    - uses: actions/upload-artifact@v2
      with:
        name: apk_aar
        path: |
          **/*.apk
          **/*.aar
