name: iOS tests

on: [ push ]

jobs:
  jobIosTests:
    runs-on: macos-11

    steps:
      - uses: devbotsxyz/xcode-select@v1

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - run: bash ./gradlew packForXcode createSwiftPackage --stacktrace

      - run: xcodebuild -project "iosApp/iosApp.xcodeproj" -scheme iosApp test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: tests.xcresult
          path: /Users/runner/Library/Developer/Xcode/DerivedData/*/Logs/Test/*.xcresult

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: spm
          path: shared/build/spm/
